[map]
size = 16384

# y
snow_start = 0
snow_end = 4096

grassland_start = 4096
grassland_end = 8192

desert_start = 8192
desert_end = 12288

lava_start = 12288
lava_end = 16384

# x
ocean_start_x = 10240
ocean_end_x = 16384

[players]
# need to fix these..
update_dt = 0.45
player_max_speed = 45.0
player_acceleration = 120.0
player_friction = 90.0

[entities]
# objects
trees_per_chunk = 9
bushes_per_chunk = 3
stones_per_chunk = 4
gold_per_chunk = 1 # later move to world, 7 gold in whole map

[animals]
max_fish_alive = 2048
max_wolf = 32
fish_turn_factor = 2.0
